name: ebuild-test

on:
  push :
  pull_request:

jobs:
  repoman:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: hacking-gentoo/action-repoman@master
  build-alt:
    container: gentoo/stage3-amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: hacking-gentoo/action-fetch-portage@v1.0.0
    - name: prepare environment
      run: |
        mkdir --parent --verbose /etc/portage/repos.conf
        echo '[trpasle]' > /etc/portage/repos.conf/trpasle-overlay.conf
        echo "$GITHUB_WORKSPACE" >> /etc/portage/repos.conf/trpasle-overlay.conf
        eselect profile set default/linux/amd64/17.1
    - name: emerge
      run: |
        mkdir --parent --verbose /etc/portage/package.accept_keywords
        export EMERGE_DEFAULT_OPTS=--jobs
        echo "sci-misc/alt" ~amd64 >> /etc/portage/package.accept_keywords/testbuild
        USE='-ncurses -qt5' emerge --oneshot dev-util/cmake
        emerge sci-misc/alt
