name: ebuild-test

on:
  push :
  pull_request:

jobs:
  repoman:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: hacking-gentoo/action-repoman@master
  build-alt:
    container: gentoo/stage3-amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: prepare environment
      run: |
        mkdir --parent --verbose /var/db/repos/gentoo
        emerge-webrsync --quiet
        mkdir --parent --verbose /etc/portage/repos.conf
        echo '[trpasle]' > /etc/portage/repos.conf/trpasle-overlay.conf
        echo "location = $GITHUB_WORKSPACE" >> /etc/portage/repos.conf/trpasle-overlay.conf
        eselect profile set default/linux/amd64/17.1
        echo 'EMERGE_DEFAULT_OPTS="--jobs --autounmask-write=y --autounmask-use=y --autounmask=y --ask=n"' >> /etc/portage/make.conf
        echo 'CONFIG_PROTECT_MASK="/etc/portage"' >> /etc/portage/make.conf
        mkdir --parent --verbose /etc/portage/package.accept_keywords
        echo "sci-misc/alt ~amd64" >> /etc/portage/package.accept_keywords/testbuild
        echo "sys-devel/gcc ~amd64" >> /etc/portage/package.accept_keywords/testbuild
        mkdir --parent --verbose /etc/portage/package.use/
        echo '>=dev-util/cmake-3.16.5 qt5
        >=dev-libs/libpcre2-10.34 pcre16
        >=x11-libs/libxkbcommon-0.10.0 X
        >=media-libs/gd-2.2.5-r2 jpeg truetype png fontconfig
        >=media-libs/libglvnd-1.3.1 X
        media-gfx/graphviz X' > /etc/portage/package.use/alt
        echo 'FEATURES="-sandbox -usersandbox"' >> /etc/portage/make.conf
    - name: emerge
      run: |
        USE='-ncurses -qt5 -test' emerge --oneshot dev-util/cmake
        USE='-test' emerge --onlydeps sci-misc/alt
        FEATURES=test emerge sci-misc/alt
  build-rememberthemilk:
    container: gentoo/stage3-amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: prepare environment
      run: |
        mkdir --parent --verbose /var/db/repos/gentoo
        emerge-webrsync --quiet
        mkdir --parent --verbose /etc/portage/repos.conf
        echo '[trpasle]' > /etc/portage/repos.conf/trpasle-overlay.conf
        echo "location = $GITHUB_WORKSPACE" >> /etc/portage/repos.conf/trpasle-overlay.conf
        eselect profile set default/linux/amd64/17.1
        echo 'EMERGE_DEFAULT_OPTS="--jobs --autounmask-write=y --autounmask-use=y --autounmask=y --ask=n"' >> /etc/portage/make.conf
        echo 'CONFIG_PROTECT_MASK="/etc/portage"' >> /etc/portage/make.conf
        mkdir --parent --verbose /etc/portage/package.accept_keywords
        echo "gui-apps/rememberthemilk" ~amd64 >> /etc/portage/package.accept_keywords/testbuild
        mkdir --parent --verbose /etc/portage/package.use/
        echo '>=app-text/ghostscript-gpl-9.50 cups
                >=media-libs/libglvnd-1.3.1 X
                >=x11-libs/cairo-1.16.0-r3 X' > /etc/portage/package.use/rememberthemilk
        mkdir --parent --verbose /etc/portage/package.license
        echo 'gui-apps/rememberthemilk all-rights-reserved' > /etc/portage/package.license/rememberthemilk
        echo 'FEATURES="-sandbox -usersandbox"' >> /etc/portage/make.conf
    - name: emerge
      run: |
        USE='-test' emerge --onlydeps gui-apps/rememberthemilk
        FEATURES=test emerge gui-apps/rememberthemilk
  build-xmind:
    container: gentoo/stage3-amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: prepare environment
      run: |
        mkdir --parent --verbose /var/db/repos/gentoo
        emerge-webrsync --quiet
        mkdir --parent --verbose /etc/portage/repos.conf
        echo '[trpasle]' > /etc/portage/repos.conf/trpasle-overlay.conf
        echo "location = $GITHUB_WORKSPACE" >> /etc/portage/repos.conf/trpasle-overlay.conf
        eselect profile set default/linux/amd64/17.1
        echo 'EMERGE_DEFAULT_OPTS="--jobs --autounmask-write=y --autounmask-use=y --autounmask=y --ask=n"' >> /etc/portage/make.conf
        echo 'CONFIG_PROTECT_MASK="/etc/portage"' >> /etc/portage/make.conf
        mkdir --parent --verbose /etc/portage/package.accept_keywords
        echo "app-misc/xmind" ~amd64 >> /etc/portage/package.accept_keywords/testbuild
        echo 'app-misc/xmind XPLA no-source-code' > /etc/portage/package.license/xmind
        echo 'FEATURES="-sandbox -usersandbox"' >> /etc/portage/make.conf
    - name: emerge
      run: |
        USE='-test' emerge --onlydeps app-misc/xmind
        FEATURES=test emerge app-misc/xmind
