name: ebuild-test

on:
  push :
  pull_request:

jobs:
  repoman:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: hacking-gentoo/action-repoman@master
  build-alt:
    container: gentoo/stage3-amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: prepare environment
      run: |
        mkdir --parent --verbose /var/db/repos/gentoo
        emerge-webrsync --quiet
        mkdir --parent --verbose /etc/portage/repos.conf
        echo '[trpasle]' > /etc/portage/repos.conf/trpasle-overlay.conf
        echo "location = $GITHUB_WORKSPACE" >> /etc/portage/repos.conf/trpasle-overlay.conf
        eselect profile set default/linux/amd64/17.1
        echo 'FEATURES="-sandbox -usersandbox"' >> /etc/portage/make.conf
        echo 'EMERGE_DEFAULT_OPTS="--jobs --autounmask-write=y --autounmask-use=y --autounmask=y --ask=n"' >> /etc/portage/make.conf
        echo 'CONFIG_PROTECT_MASK="/etc/portage"' >> /etc/portage/make.conf
        mkdir --parent --verbose /etc/portage/package.accept_keywords
        echo "sci-misc/alt" ~amd64 >> /etc/portage/package.accept_keywords/testbuild
        mkdir --parent --verbose /etc/portage/package.use/
    - name: emerge
      run: |
        USE='-ncurses -qt5' emerge --oneshot dev-util/cmake
        dispatch-conf
        echo before
        emerge sci-misc/alt
        dispatch-conf
        echo between
